
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '889D9D1351C81BFF184D69E785D03F09'
    
_lr_action_items = {'SYMBOL':([0,4,5,7,],[2,2,2,2,]),'$end':([1,2,3,6,9,10,11,],[0,-2,-1,-5,-6,-4,-3,]),'CONCAT':([1,2,3,6,8,9,10,11,],[5,-2,-1,-5,5,-6,5,-3,]),'STAR':([1,2,3,6,8,9,10,11,],[6,-2,-1,-5,6,6,6,-3,]),'RPAREN':([2,3,6,8,9,10,11,],[-2,-1,-5,11,-6,-4,-3,]),'UNION':([1,2,3,6,8,9,10,11,],[7,-2,-1,-5,7,-6,-4,-3,]),'LPAREN':([0,4,5,7,],[4,4,4,4,]),'EPSILON':([0,4,5,7,],[3,3,3,3,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,5,7,],[1,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> EPSILON','expression',1,'p_expression_epsilon','re_to_ast.py',88),
  ('expression -> SYMBOL','expression',1,'p_expression_symbol','re_to_ast.py',92),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_paren','re_to_ast.py',96),
  ('expression -> expression UNION expression','expression',3,'p_expression_union','re_to_ast.py',100),
  ('expression -> expression STAR','expression',2,'p_expression_star','re_to_ast.py',104),
  ('expression -> expression CONCAT expression','expression',3,'p_expression_concat','re_to_ast.py',108),
]
